project:
  type: website
  output-dir: _site

website:
  favicon: fig/favicon2.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - text: "Teaching"      
        href: teaching.qmd  
      - text: "Software"
        href: software.qmd

format:
  html:
    theme: minimal  # "cosmo", "journal", or "minimal" are good for academics
    css: styles.css
    toc: true